### ISSUE TITLE
Getting 400112 error code in streaming.task api

### ISSUE THREAD

**Issue by nokhalal-mahato** [HeyGen-Official/StreamingAvatarSDK#24]
I am getting 401 status code when doing the steaming.task api call. I have ensured i am passing the correct auth token in header.
Below is the request and response:-

Request - {
    "text": "Hello world"
}

Response - {
    "code": 400112,
    "message": "Unauthorized"
}

**Comment by nokhalal-mahato** [comment]
We debug and found session_id was missing in the request object when we were getting this issue. It was a bug in our code we have fixed it.

Closing this issue.

**Comment by weirenlan** [comment]
@nokhalal-mahato  hi 
Do you meet the same response with this request?

```
curl -X POST https://api.heygen.com/v1/streaming.create_token -H "x-api-key: <your_api_key>"
```
