### ISSUE TITLE
Compatibility with Vue.js project?

### ISSUE THREAD

**Issue by AmoMTL** [HeyGen-Official/StreamingAvatarSDK#29]
can this SDK be used with a Vue.js project?

**Comment by jobyrao** [comment]
I think so. have you tried it?

**Comment by jobyrao** [comment]
> can this SDK be used with a Vue.js project?

I think so. have you tried it?

**Comment by AmoMTL** [comment]
yes was able to integrate by slightly modifying the existing SDK
